/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as CreatePostRouteImport } from "./routes/create-post";
import { Route as ApplyReviewerRouteImport } from "./routes/apply-reviewer";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PostPostIdRouteImport } from "./routes/post.$postId";

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const CreatePostRoute = CreatePostRouteImport.update({
  id: "/create-post",
  path: "/create-post",
  getParentRoute: () => rootRouteImport,
} as any);
const ApplyReviewerRoute = ApplyReviewerRouteImport.update({
  id: "/apply-reviewer",
  path: "/apply-reviewer",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: "/post/$postId",
  path: "/post/$postId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/apply-reviewer": typeof ApplyReviewerRoute;
  "/create-post": typeof CreatePostRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/post/$postId": typeof PostPostIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/apply-reviewer": typeof ApplyReviewerRoute;
  "/create-post": typeof CreatePostRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/post/$postId": typeof PostPostIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/apply-reviewer": typeof ApplyReviewerRoute;
  "/create-post": typeof CreatePostRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/post/$postId": typeof PostPostIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/apply-reviewer"
    | "/create-post"
    | "/dashboard"
    | "/login"
    | "/register"
    | "/post/$postId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin"
    | "/apply-reviewer"
    | "/create-post"
    | "/dashboard"
    | "/login"
    | "/register"
    | "/post/$postId";
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/apply-reviewer"
    | "/create-post"
    | "/dashboard"
    | "/login"
    | "/register"
    | "/post/$postId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRoute;
  ApplyReviewerRoute: typeof ApplyReviewerRoute;
  CreatePostRoute: typeof CreatePostRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  PostPostIdRoute: typeof PostPostIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create-post": {
      id: "/create-post";
      path: "/create-post";
      fullPath: "/create-post";
      preLoaderRoute: typeof CreatePostRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/apply-reviewer": {
      id: "/apply-reviewer";
      path: "/apply-reviewer";
      fullPath: "/apply-reviewer";
      preLoaderRoute: typeof ApplyReviewerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/post/$postId": {
      id: "/post/$postId";
      path: "/post/$postId";
      fullPath: "/post/$postId";
      preLoaderRoute: typeof PostPostIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyReviewerRoute: ApplyReviewerRoute,
  CreatePostRoute: CreatePostRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PostPostIdRoute: PostPostIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.jsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
